### ISSUE TITLE
crash using a symbol that worked in 1.5

### ISSUE THREAD

**Issue by pcause** [aldrinzigmundv/zigfi#2]
try:

zigfi new test 9984.T

it crashes.  the symbol used to work in 1.5.  went to yahoo finance and entered in the search bar and it found it and displayed results

**Comment by aldrinzigmundv** [comment]
Working on it. The issue is coming from the crate that I used to fetch Yahoo Finance data. It crashes whenever `adjclose` is missing from the response.

The ticker wouldn't also work in `v1.5.0`. The only reason it looked like it did is `zigfi new` only requested to see if there will be an error but didn't really capture the data, which it now does as it is now treating it the same way as `zigfi show`.

I don't know but other tickers for Softbank might work for now but I'm working on an immediate fix.

**Comment by aldrinzigmundv** [comment]
It looks like there's something with the Yahoo Finance API. The value `adjclose` for some reason is available and is working now. I'm using v2.0.1.

I'm working on a way to prevent this in the future though. 😉 Don't hesitate to message me here with the ticker if you get another occurrence of the same issue. Thanks.
![image](https://user-images.githubusercontent.com/77566475/148913306-718b7411-7cf8-4ebf-8260-2bdcc44c2f00.png)

**Comment by pcause** [comment]
seems fixed and the new output works. thanks!
